# -*- coding: utf-8 -*-
"""KMeans Cluster analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YOirUcOfta8AecIPDc_urwzSGoGHBXJH
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data

scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

df=sns.load_dataset("iris")

scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

print(df.head())

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

# Load Iris dataset
iris = load_iris()

# Create DataFrame
df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

# Display data
print(df.head())

# Select features
X = df.copy()

# Standardize features
scaler = StandardScaler()
x_scaled = scaler.fit_transform(X)

# ---------------------------------------
# Elbow Method
# ---------------------------------------

wcss = []

for k in range(1, 11):

    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    kmeans.fit(x_scaled)

    wcss.append(kmeans.inertia_)

# Plot
plt.figure(figsize=(8, 5))

plt.plot(
    range(1, 11),
    wcss,
    marker='o',
    linewidth=2
)

plt.title("Elbow Method for K-Means")
plt.xlabel("Number of Clusters (K)")
plt.ylabel("WCSS")
plt.xticks(range(1, 11))
plt.grid(True)

plt.show()

kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

clusters = kmeans.fit_predict(X_scaled)

df['Cluster'] = clusters

score=silhouette_score(X_scaled,clusters)
print("\nSilhouette Score:",score)

feature_names = iris.feature_names

plt.figure(figsize=(8, 6))

sns.scatterplot(
    x=X_scaled[:, 0],
    y=X_scaled[:, 1],
    hue=clusters,
    palette="viridis",
    s=70
)

# Plot centroids
centroids = kmeans.cluster_centers_

plt.scatter(
    centroids[:, 0],
    centroids[:, 1],
    marker="X",
    s=200,
    c="red",
    label="Centroids"
)

plt.title("K-Means Clustering")
plt.xlabel(feature_names[0])
plt.ylabel(feature_names[1])
plt.legend()
plt.grid(True)

plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

for i, w in enumerate(wcss):
    print(f"For k={i+1}, WCSS = {w:.2f}")

iris = load_iris()
x = pd.DataFrame(iris.data, columns=iris.feature_names)
y = pd.Series(iris.target,name='species')
species_names = iris.target_names

print("First 5 rows:\n" , x.head())

print("First 5 rows:\n" , x.head())
print("\nMissing values:\n" ,x.isnull().sum())
print("\nData types:\n" ,x.dtypes)
print("\nDescriptive stats:\n", x.describe())

pca = PCA()
pca.fit(X_scaled)

# Scree Plot - Explained Variance by Principal Components
plt.figure(figsize=(6, 4))

plt.plot(
    range(1, len(pca.explained_variance_ratio_) + 1),
    pca.explained_variance_ratio_,
    'o-',
    color='blue'
)

plt.title('Scree Plot - Explained Variance by Principal Components')
plt.xlabel('Principal Component')
plt.ylabel('Explained Variance Ratio')
plt.grid(True)
plt.tight_layout()

plt.show()

from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

# Apply PCA with 2 components
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

# Perform K-Means clustering on the PCA-transformed data
kmeans_pca = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)
clusters_pca = kmeans_pca.fit_predict(X_pca)

# Add the PCA clusters to a DataFrame for easier plotting
df_pca = pd.DataFrame(
    data = X_pca,
    columns = ['principal component 1', 'principal component 2']
)
df_pca['cluster'] = clusters_pca

# Visualize the clusters
plt.figure(figsize=(8, 6))
sns.scatterplot(
    x='principal component 1',
    y='principal component 2',
    hue='cluster',
    data=df_pca,
    palette='viridis',
    s=100,
    alpha=0.8
)

# Plot centroids
centroids_pca = kmeans_pca.cluster_centers_
plt.scatter(
    centroids_pca[:, 0],
    centroids_pca[:, 1],
    marker='X',
    s=250,
    color='red',
    label='Centroids'
)

plt.title('K-Means Clustering with PCA (2 Components)')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(6,4))
plt.plot(range(1,len(pca.explained_variance_ratio_)+1),pca.explained_variance_ratio_,'o-',color='blue')
plt.title('scree plot = Explained Variance by Principal Componts')
plt.xlabel('Principal Components')
plt.ylabel('Explained Variance Ratio')
plt.grid(True)
plt.tight_layout()
plt.show()